matrix:
  include:
    - BUILDTYPE: Release
      IMAGE: "xyst-gnu"
      CHARM_INSTALL_DIR: "/charm-non-smp"
    - BUILDTYPE: Release
      IMAGE: "xyst-gnu"
      CHARM_INSTALL_DIR: "/charm-smp"
      POSTFIX_RUNNER_ARGS: "+setcpuaffinity"
    #- BUILDTYPE: Debug
    #  IMAGE: "xyst-gnu"
    #  CHARM_INSTALL_DIR: "/charm-non-smp"
    #- BUILDTYPE: Debug
    #  IMAGE: "xyst-clang"
    #  CHARM_INSTALL_DIR: "/charm-non-smp"

pipeline:
  build:
    image: jbakosi/${IMAGE}
    #pull: true
    commands:
     - mkdir build && cd build && cmake -DCHARM_INSTALL_DIR=${CHARM_INSTALL_DIR} -Wno-dev -DCMAKE_BUILD_TYPE=${BUILDTYPE} -DRUNNER=mpirun -DRUNNER_NCPUS_ARG=-n -DRUNNER_ARGS="--allow-run-as-root --bind-to none -oversubscribe" -DPOSTFIX_RUNNER_ARGS=${POSTFIX_RUNNER_ARGS} ../src && make -sj2

  test:
    image: jbakosi/${IMAGE}
    commands:
      - cd build && mpirun --allow-run-as-root -n 2 Main/unittest -q && ctest -j2 --output-on-failure
