matrix:
  include:
    - BUILDTYPE: Release
      COMPILER: gnu
    - BUILDTYPE: Release
      COMPILER: gnu
      SMP: on
   # - BUILDTYPE: Debug
   #   COMPILER: clang
   #   smp: ""

pipeline:
  build:
    image: jbakosi/xyst-gnu${SMP:+-smp}
    #pull: true
    commands:
     - mkdir build && cd build && cmake ${SMP:+-DSMP=on} -Wno-dev -DCMAKE_BUILD_TYPE=${BUILDTYPE} -DTPL_DIR=/xyst/external/install/${COMPILER} -DRUNNER=mpirun -DRUNNER_NCPUS_ARG=-n -DRUNNER_ARGS="--allow-run-as-root -oversubscribe" ../src && make -sj2
    when:
      matrix:
        COMPILER: gnu

  #build-clang:
  #  image: jbakosi/xyst-clang
  #  #pull: true
  #  commands:
  #   - mkdir build && cd build && cmake -Wno-dev -DCMAKE_BUILD_TYPE=${BUILDTYPE} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DTPL_DIR=/xyst/external/install/${COMPILER} -DRUNNER=mpirun -DRUNNER_NCPUS_ARG=-n -DRUNNER_ARGS="--allow-run-as-root --bind-to none -oversubscribe" .. && make -sj2
  #  when:
  #    matrix:
  #      COMPILER: clang

  test:
    image: jbakosi/xyst-${COMPILER}
    commands:
      - cd build && mpirun --allow-run-as-root -n 2 Main/unittest -v -q && ctest -j2 --output-on-failure -LE extreme
