matrix:
  include:
    - BUILDTYPE: Release
      IMAGE: "xyst-gnu"
      TPL_DIR: "/xyst/external/install/gnu"
    - BUILDTYPE: Release
      IMAGE: "xyst-gnu-smp"
      TPL_DIR: "/xyst/external/install/gnu-smp"
      SMP: on
      POSTFIX_RUNNER_ARGS: "+setcpuaffinity"
    - BUILDTYPE: Debug
      IMAGE: "xyst-clang"
      TPL_DIR: "/xyst/external/install/clang"

pipeline:
  build:
    image: jbakosi/${IMAGE}
    #pull: true
    commands:
     - mkdir build && cd build && cmake -DSMP=${SMP} -Wno-dev -DCMAKE_BUILD_TYPE=${BUILDTYPE} -DTPL_DIR=${TPL_DIR} -DRUNNER_ARGS="--allow-run-as-root --bind-to none -oversubscribe" -DPOSTFIX_RUNNER_ARGS=${POSTFIX_RUNNER_ARGS} ../src && make -sj2 meshconv

  test:
    image: jbakosi/${IMAGE}
    commands:
      #- cd build && mpirun --allow-run-as-root -n 2 Main/unittest -v -q && ctest -j2 --output-on-failure -L meshconv
      - cd build && ctest -j2 --output-on-failure -L meshconv
